### ISSUE TITLE
vc 9 and openmp 5.0.0

### ISSUE THREAD

**Issue by moorepants** [conda-forge/openmp-feedstock#21]
Issue:

I'm getting this error:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - openblas -> libflang[version='>=5.0.0'] -> openmp==5.0.0 -> vc=14
  - vc=9
Use "conda search <package> --info" to see the dependencies for each package.
```

when trying to build on windows with openblas and libflang for python 2.7 support.

Is this possible? Is there an openmp for vc 9?

Feedstock build here: https://github.com/conda-forge/slycot-feedstock/pull/18

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by isuruf** [comment]
No, it's not. flang and openmp are vc14 only.

**Comment by moorepants** [comment]
Ok, so if you want to use flang you can't support py 27 builds?

**Comment by isuruf** [comment]
Yes. Only py>=35 builds.

**Comment by moorepants** [comment]
ok, thanks
