### ISSUE TITLE
OpenMP 9.0

### ISSUE THREAD

**Issue by npavlovikj** [conda-forge/openmp-feedstock#27]
Hi,

Is there a reason why `openmp` was removed for 9.0?
I have a package that fails to be installed on MacOS with:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - r-fastbaps -> r-genie -> llvm-openmp[version='>=9.0.0'] -> openmp[version='9.0.0|9.0.0.*']
```
so, I was wondering if I should pin `llvm-openmp` to <9.0, or wait for `openmp` 9.0.
I don't have `openmp` as an explicit dependency, so it is probably installed from some of the other packages.

Thank you,
Natasha

**Comment by jaimergp** [comment]
I am also curious!

**Comment by isuruf** [comment]
Try to figure out which package is depending on `openmp` and change the name to `llvm-openmp`.

**Comment by h-vetinari** [comment]
closing this as obsolete
