### ISSUE TITLE
Segfault when using llvm-openmp-12.0.1 on macos

### ISSUE THREAD

**Issue by jeremiedbb** [conda-forge/openmp-feedstock#50]
We use clang and llvm-openmp from conda-forge on macos in the CI of a project (https://github.com/joblib/threadpoolctl). It used to work with the version 11.1.0. 

The installation completes fine but we have a segfault at runtime when trying to run a simple openmp based piece of parallel code.

Here is the difference of the 2 environments between when it used to work and now:
**before**
    intel-openmp-2021.2.0      |     hecd8cb5_564         942 KB
    llvm-openmp-11.1.0         |       hda6cdc1_1         268 KB  conda-forge
    mkl-2021.2.0               |     hecd8cb5_269       100.0 MB
    mkl-service-2.3.0          |   py39h9ed2024_1          44 KB
    mkl_random-1.2.1           |   py39hb2f4e1b_2         282 KB
**after**
    fortran-compiler-1.0.3     |       h4f947d3_0           5 KB  conda-forge
    intel-openmp-2021.3.0      |    hecd8cb5_3375         950 KB
    llvm-openmp-12.0.1         |       hda6cdc1_0         286 KB  conda-forge
    mkl-2021.3.0               |     hecd8cb5_517       100.4 MB
    mkl-service-2.4.0          |   py39h9ed2024_0          45 KB
    mkl_random-1.2.2           |   py39hb2f4e1b_0         285 KB

pinning the version of llvm-openmp to 11.1.0 solves the issue.

Thanks

**Comment by isuruf** [comment]
Can you share an example program and a backtrace?

**Comment by jeremiedbb** [comment]
Unfortunately I've not been able to reproduce on the mac I had access to. It happens on our CI with a different version of macos. I'll try to come up with one asap.

**Comment by jeremiedbb** [comment]
The conda env for which our CI fails is mixing packages from the default channel with compilers and llvm-openmp from the conda-forge channel. Using all packages from the conda-forge channel no longer triggers the issue.

Given that it's not advised to mix packages from different channels, I guess this is a wont fix. Feels like this issue can be closed unless you think this configuration should work anyway (`conda create -n tmp python numpy scipy blas[build=mkl] conda-forge::compilers conda-forge::llvm-openmp`)

**Comment by isuruf** [comment]
Ah, that might have been a bad interaction between `llvm-openmp` and `intel-openmp`. At conda-forge, we are enforcing that one is used (by making MKL use llvm-openmp as well), while in defaults, it's not.
