### ISSUE TITLE
DLL load error - incompatible libiomp5md.dll

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/openmp-feedstock#8]
Both this (`openmp`) package and the defaults `intel-openmp` install `libiomp5md.dll` into `/Library/bin`:

```
λ ls C:\Miniconda3\pkgs\openmp-6.0.0-vc14_0\Library\bin

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---l       11/03/2018     10:48         615424 libiomp5md.dll
-a---l       11/03/2018     10:48         615424 libomp.dll
```
```
λ ls C:\Miniconda3\pkgs\intel-openmp-2018.0.0-8\Library\bin

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---l       23/03/2018      2:22        1343744 libiomp5md.dll
-a---l       23/03/2018      2:22        3755008 libiomp5md.pdb
-a---l       23/03/2018      2:22          81664 libiompstubs5md.dll
```
This means that installing one when the other is already present will ***overwrite*** the existing `libiomp5md.dll`.

Unfortunately these two dlls do not appear to be compatible as using the `libiomp5md.dll` provided by the `openmp` package will break `pytorch`, resulting in a DLL load error:
```
ImportError: DLL load failed: The operating system cannot run %1.
```

Tested on win64/py36

**Comment by dhirschfeld** [comment]
***Repro:***

Create a clean `pytorch` environment from defaults:
```
λ conda create -n torch --override-channels -c pytorch -c defaults python=3.6* pytorch-cpu --yes
```
Activate and test:
```
λ activate torch

(torch) λ  python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> exit()
```
Install `openmp` from conda-forge and `pytorch` breaks:
```
(torch) λ conda install --force conda-forge::openmp --yes
Solving environment: done

## Package Plan ##

  environment location: C:\Miniconda3\envs\torch

  added / updated specs:
    - conda-forge::openmp


The following NEW packages will be INSTALLED:

    llvm-meta: 6.0.0-0      conda-forge
    openmp:    6.0.0-vc14_0 conda-forge [vc14]

Preparing transaction: done
Verifying transaction: /
SafetyError: The package for openmp located at C:\Miniconda3\pkgs\openmp-6.0.0-vc14_0
appears to be corrupted. The path 'Library/bin/libiomp5md.dll'
has a sha256 mismatch.
  reported sha256: 2945f98e342aaedf335dee679e66e786f336d4bea47c50d99cbbc220786cf74e
  actual sha256: 46f32172318c305e29edf907f6cc9e8e810bdff41943f2ee76e3f10abc554caf

ClobberError: The package 'conda-forge::openmp-6.0.0-vc14_0' cannot be installed due to a
path collision for 'library/bin/libiomp5md.dll'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.
```

Ok, that didn't work! :stuck_out_tongue_winking_eye:

I guess it's very good that conda doesn't allow you to shoot yourself in the foot, however that begs the question as to how I ended up with both in my environment :confused: 

Maybe there's an install path that doesn't trigger the `ClobberError`.

**Comment by jakirkham** [comment]
Thanks @dhirschfeld.

When I read this was thinking, "Huh? That's weird. Why would `openmp`, which installs `libomp.dll` (or similar on other OSes), install `libiomp5md.dll`?" However it does seem to be the case it does this and it even installs `libgomp.so` (or similar) on Unix-y platforms. On Unix platforms, these are installed as symlinks. Expect the same sort of thing is being done here on Windows (though likely through hard linking/copying).

FWIW this isn't some custom build step we added in. It is something that `openmp` seems to do all by itself. That said, I'd be in favor of disabling or manually removing these symlinks as part of the build.

How do you feel about doing a PR?

**Comment by dhirschfeld** [comment]
Just checked - if I install an older conda `4.3.34` you don't get the clobber error:
```
(torch) λ conda install --force --override-channels -c conda-forge openmp --yes
Fetching package metadata .....................
Solving package specifications: .

Package plan for installation in environment C:\Miniconda3\envs\torch:

The following NEW packages will be INSTALLED:

    openmp: 6.0.0-vc14_0 conda-forge [vc14]

(torch) λ python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\envs\torch\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.
>>> exit()
```
...so it's likely I clobbered my environment using an older conda.

**Comment by dhirschfeld** [comment]
I'm not 100% sure I understand what's required but I can see if I can make a start...
